require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FuelStation' do

  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])


  # Permissions
  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"


  # Pods for FuelStation

  target 'FuelStation-tvOS' do
    target 'FuelStation-tvOSTests' do
      inherit! :search_paths
      # Pods for testing
    end
  end

  target 'FuelStationTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end

  # Custom
  post_install do |pi|
    pi.pods_project.targets.each do |t|
      t.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
  end

end


